package uk.ac.liv.comp201;

public enum ResponseCode {
	CARD_NOT_FOUND,
	INVALID_CARD,
	BAD_FIRE_CODE,
	BAD_BURGLARY_CODE,
	OK,
	INVALID_FIRE_CODE,
	INVALID_BURGLARY_CODE,
	INVALID_CARD_ID_LENGTH,
	INVALID_CARD_ID,
	CARD_LOCKED
}
